## Gather instance metadata on the AWS layer
- hosts: localhost
  vars_files:
    - my-vars.yml
  tasks:
    - name: Gather ec2 facts
      ec2_remote_facts:
        region: "{{ ec2_region }}"
        filters:
          subnet-id: "{{ ec2_vpc_subnet_id }}"
      register: ec2_info
    - name: Set instance info as fact
      set_fact:
        ec2_info: "{{ ec2_info.instances }}"
## Add the info to the hosts file
- hosts: "{{ ec2_host }}"
  vars_files:
    - my-vars.yml
  sudo: yes
  tasks:
    - name: Remove any previous hosts entries with this ip
      lineinfile:
        dest: /etc/hosts
        regexp: "^{{ item.private_ip_address }}"
        state: absent
        backup: yes
      with_items: "{{ hostvars['localhost']['ec2_info'] }}"
    - name: Remove any previous hosts entries with this name, exlcuding localhost entries
      lineinfile:
        dest: /etc/hosts
        regexp: "^(?!((127\\.0\\.0\\.1)|(::1)))\\s{{ item.tags.Name }}"
        state: absent
        backup: yes
      with_items: "{{ hostvars['localhost']['ec2_info'] }}"
    - name: Add new server to hosts entry
      lineinfile:
        dest: /etc/hosts
        line: "{{ item.private_ip_address }} {{ item.tags.Name }}"
        state: present
        backup: yes
      with_items: "{{ hostvars['localhost']['ec2_info'] }}"
